2024-07-16 06:57:14,804 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO - Span: transcribe_empty
2024-07-16 06:57:14,804 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Trace ID: 305296408031943654871564221517464566860
2024-07-16 06:57:14,804 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Span ID: 9905486906442837881
2024-07-16 06:57:14,804 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Parent ID: 15982361673244479658
2024-07-16 06:57:14,804 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Start time: 2024-07-16 06:57:14.689
2024-07-16 06:57:14,804 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   End time: 2024-07-16 06:57:14.803
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Duration: 0.114s
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Attributes:
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     function_name: transcribe_empty
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Events:
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     Starting empty transcription at 2024-07-16 06:57:14.689 (+0.000s):
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     Reading transcription file at 2024-07-16 06:57:14.689 (+0.000s):
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     Sampling transcription list at 2024-07-16 06:57:14.748 (+0.059s):
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     Empty transcription completed at 2024-07-16 06:57:14.748 (+0.059s):
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     exception at 2024-07-16 06:57:14.803 (+0.114s):
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.type: KeyError
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.message: 'run_id'
2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.stacktrace: Traceback (most recent call last):
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/sdk/trace/__init__.py", line 1091, in start_as_current_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 363, in wrapper
    run_id = span.attributes["run_id"]
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/attributes/__init__.py", line 163, in __getitem__
    return self._dict[key]
           ~~~~~~~~~~^^^^^
KeyError: 'run_id'

2024-07-16 06:57:14,805 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.escaped: False
2024-07-16 06:57:14,806 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO - 
2024-07-16 06:57:14,808 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO - Span: Step :transcribe
2024-07-16 06:57:14,808 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Trace ID: 305296408031943654871564221517464566860
2024-07-16 06:57:14,808 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Span ID: 15982361673244479658
2024-07-16 06:57:14,808 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Parent ID: 5969523260776009323
2024-07-16 06:57:14,808 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Start time: 2024-07-16 06:57:14.688
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   End time: 2024-07-16 06:57:14.808
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Duration: 0.120s
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Attributes:
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     run_id: 3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     input_name: first_args
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     function: transcribe_empty
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Events:
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     exception at 2024-07-16 06:57:14.808 (+0.120s):
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.type: KeyError
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.message: 'run_id'
2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.stacktrace: Traceback (most recent call last):
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/sdk/trace/__init__.py", line 1091, in start_as_current_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 463, in run
    self._output = await asyncio.to_thread(self.f, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 363, in wrapper
    run_id = span.attributes["run_id"]
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/attributes/__init__.py", line 163, in __getitem__
    return self._dict[key]
           ~~~~~~~~~~^^^^^
KeyError: 'run_id'

2024-07-16 06:57:14,809 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.escaped: False
2024-07-16 06:57:14,810 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO - 
2024-07-16 06:57:14,811 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO - Span: Pipeline :pipe
2024-07-16 06:57:14,811 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Trace ID: 305296408031943654871564221517464566860
2024-07-16 06:57:14,811 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Span ID: 5969523260776009323
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Parent ID: None
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Start time: 2024-07-16 06:57:14.688
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   End time: 2024-07-16 06:57:14.811
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Duration: 0.123s
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Attributes:
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     run_id: 3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -   Events:
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     exception at 2024-07-16 06:57:14.810 (+0.122s):
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.type: KeyError
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.message: 'run_id'
2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.stacktrace: Traceback (most recent call last):
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 240, in start
    result = await self.run(input, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 266, in run
    result = await child.run(input, child.input_name, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 463, in run
    self._output = await asyncio.to_thread(self.f, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 363, in wrapper
    run_id = span.attributes["run_id"]
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/attributes/__init__.py", line 163, in __getitem__
    return self._dict[key]
           ~~~~~~~~~~^^^^^
KeyError: 'run_id'

2024-07-16 06:57:14,812 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.escaped: False
2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     Pipeline : pipe execution completed at 2024-07-16 06:57:14.810 (+0.122s):
2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     No output due to exception at 2024-07-16 06:57:14.810 (+0.122s):
2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -     exception at 2024-07-16 06:57:14.811 (+0.123s):
2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.type: KeyError
2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.message: 'run_id'
2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.stacktrace: Traceback (most recent call last):
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/sdk/trace/__init__.py", line 1091, in start_as_current_span
    yield span
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 240, in start
    result = await self.run(input, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 266, in run
    result = await child.run(input, child.input_name, run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 463, in run
    self._output = await asyncio.to_thread(self.f, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/anaconda3/envs/gitverse/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/workflows/pipeline.py", line 363, in wrapper
    run_id = span.attributes["run_id"]
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/chrysostomebeltran/Downloads/exercise/.venv/lib/python3.12/site-packages/opentelemetry/attributes/__init__.py", line 163, in __getitem__
    return self._dict[key]
           ~~~~~~~~~~^^^^^
KeyError: 'run_id'

2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO -       exception.escaped: False
2024-07-16 06:57:14,813 - run_3dfddd79-0e3d-47a0-ae56-ec4b6b248d8f - INFO - 
